# Модуль NumPy

In [1]:
print("Hello")

Hello


In [2]:
#  установка NumPy
!pip install numpy

In [3]:
# импортирование модуля (библиотеками, фремворками)
import numpy as np

- создание массивов

In [4]:
#  создание вектор - строку (1 - мерный массив) из строки
my_list = [1,2,3,4,5]
my_list 

[1, 2, 3, 4, 5]

In [5]:
 np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
# создание массива (ветор-строки) из нулей 
z = np.zeros(20)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [9]:
# создание вектор-столбца из нулей
# (кол-во срок, кол-во стобцов)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# создание матрицы из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# метод который создает вектор-строку со значениями из линейной последовательности 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [16]:
# вектор-строка со значениями из равномерного распределения 
# например от 0 до 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
# случаные значения из равномерного распределения от 0 до 1
np.random.random(5)

array([0.66926072, 0.39508441, 0.24423586, 0.11980845, 0.39569077])

In [20]:
np.random.random((3,3))

array([[0.12796014, 0.96609219, 0.2117336 ],
       [0.92441162, 0.19269344, 0.90314747],
       [0.43387916, 0.01824136, 0.71103378]])

In [21]:
# случайные целый значения
# случайное  число от 0 до 10
np.random.randint(10)

1

In [22]:
# вектор-строка со знач. от 0 до 10 размером (длиной) 5
np.random.randint(10,size=5)

array([8, 5, 2, 9, 0])

In [26]:
# матрица формой 2 на 3 со слууч. знач. от 10 до 20
np.random.randint(10, 20, size=(2,3))

array([[17, 15, 17],
       [15, 18, 12]])

- атрибуты


In [29]:
a=np.random.randint(10, size=(2,3))
a

array([[5, 0, 8],
       [2, 9, 1]])

In [30]:
# размерность массива - кол-во измерений/осей
a.ndim

2

In [31]:
# форма массива
a.shape

(2, 3)

In [32]:
# количество всех элементов
a.size

6

In [33]:
# тип значений
a.dtype

dtype('int32')

In [37]:
a.astype("int8")

array([[5, 0, 8],
       [2, 9, 1]], dtype=int8)

- индексация

In [1]:
import numpy as np

In [2]:
a2 = np.random.randint(10, size=10)
a2

array([6, 4, 4, 9, 0, 9, 9, 6, 1, 3])

In [3]:
# чтение значений
a2[0]

6

In [4]:
# изменение значений
a2[1]=10
a2

array([ 6, 10,  4,  9,  0,  9,  9,  6,  1,  3])

In [7]:
a3=np.random.randint(10, size=(3, 5))
a3

array([[8, 8, 6, 8, 7],
       [1, 2, 2, 4, 8],
       [6, 5, 7, 6, 0]])

In [8]:
# стандартный питоновский способ
a3[0][2]

6

In [9]:
# способ NumPy
a3[0, 2]

6

- срезы

In [10]:
# срезх по строкам 
a3[1: ]

array([[1, 2, 2, 4, 8],
       [6, 5, 7, 6, 0]])

In [11]:
a3[1:, :3]

array([[1, 2, 2],
       [6, 5, 7]])

In [12]:
a3[:, 2:]

array([[6, 8, 7],
       [2, 4, 8],
       [7, 6, 0]])

- представления (views) и копии (copies)

In [14]:
# списка
my_list=[1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [15]:
# вектор-строки
my_arr=np.array(my_list)
my_arr

array([1, 2, 3, 4, 5])

In [16]:
# срез списка
sub_list=my_list[2:]
sub_list

[3, 4, 5]

In [17]:
# срез вектор-строки
sub_arr=my_arr[2:]
sub_arr

array([3, 4, 5])

In [18]:
sub_list[0]=100
my_list

[1, 2, 3, 4, 5]

In [19]:
# массив, созданный срезом другого массива является -  представлением
# поэтому, изменения в массиве-представлении отражаются на исходный массив
sub_arr[0]=1000
my_arr

array([   1,    2, 1000,    4,    5])

In [21]:
# копия массива 
copy_arr=my_arr[:2].copy()
copy_arr

array([1, 2])

In [23]:
copy_arr[0]=10
my_arr

array([   1,    2, 1000,    4,    5])

- изменение формы

In [34]:
# одномерный массив (вектор-строка)
arr=np.arange(1, 17)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [35]:
arr.shape

(16,)

In [38]:
# изменение формы - создание вектор-столбца
arr.reshape((8, 2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [33]:
# создание формы - создание матрицы
arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- универсальные функции

In [40]:
a=np.array([1,2,3,4,5])
b=np.array([20,30,40,50,60])
print(a)
print(b)

[1 2 3 4 5]
[20 30 40 50 60]


In [41]:
# поэлементное деление
a/b

array([0.05      , 0.06666667, 0.075     , 0.08      , 0.08333333])

In [42]:
# деление на скалярное значение
a/100

array([0.01, 0.02, 0.03, 0.04, 0.05])

In [43]:
100/a

array([100.        ,  50.        ,  33.33333333,  25.        ,
        20.        ])

In [44]:
a>b

array([False, False, False, False, False])

In [45]:
a<b

array([ True,  True,  True,  True,  True])

In [46]:
a>10

array([False, False, False, False, False])

- агрегирование

In [47]:
# агрегирование - вычисление неких сводных показателей
arr_2=np.random.random(10)
arr_2

array([0.46003218, 0.3909255 , 0.15098978, 0.03505695, 0.89480686,
       0.83432066, 0.52668777, 0.04973466, 0.19609342, 0.57327134])

In [48]:
# сумма 
np.sum(arr_2)

4.111919122799504

In [49]:
# минимум
np.min(arr_2)

0.03505694895083533

In [50]:
# среднее арифметическое 
np.mean(arr_2)

0.41119191227995044

- маскирование

In [52]:
# извлечение значений, которые отвечают некоторому условию
x=np.random.randint(20, size=10)
x

array([17,  1,  7,  2,  4, 17,  0, 12, 10, 16])

In [53]:
x<5

array([False,  True, False,  True,  True, False,  True, False, False,
       False])

In [54]:
# только те значения, которые меньше 5
x[x<5]

array([1, 2, 4, 0])

In [56]:
# те значения,которые меньше 5, меняются на 0
x[x<5]=0 
x

array([17,  0,  7,  0,  0, 17,  0, 12, 10, 16])

- "прихотливая" индексация 

In [58]:
# прихотлива\ индексация - выбор значений по определенным индекса
x=np.random.randint(10, size= 7)
x

array([9, 0, 3, 1, 1, 8, 6])

In [59]:
# выбор значений по списку с индексами
x[[5,0,3]]

array([8, 9, 1])

In [61]:
# выбор значений по массиву с индексами, которые находится в переменной Indices
indices=np.array([5,0,3])
x[indices]

array([8, 9, 1])

In [67]:
x2=np.random.randint(10, size=(3,5))
x2

array([[4, 7, 4, 6, 4],
       [0, 9, 8, 9, 9],
       [6, 3, 5, 8, 5]])

In [72]:
# сочетание среза и прихотливой индексации
x2[1:, [2,0]]

array([[8, 0],
       [5, 6]])

In [74]:
x2[x2>5

array([[ True, False,  True, False,  True],
       [ True, False, False, False, False],
       [False,  True, False, False, False]])