# Модуль NumPy

In [1]:
print("Hello")

Hello


In [2]:
#  установка NumPy
!pip install numpy

In [3]:
# импортирование модуля (библиотеками, фремворками)
import numpy as np

- создание массивов

In [4]:
#  создание вектор - строку (1 - мерный массив) из строки
my_list = [1,2,3,4,5]
my_list 

[1, 2, 3, 4, 5]

In [5]:
 np.array(my_list)

array([1, 2, 3, 4, 5])

In [7]:
# создание массива (ветор-строки) из нулей 
z = np.zeros(20)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [9]:
# создание вектор-столбца из нулей
# (кол-во срок, кол-во стобцов)
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [11]:
# создание матрицы из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# метод который создает вектор-строку со значениями из линейной последовательности 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [16]:
# вектор-строка со значениями из равномерного распределения 
# например от 0 до 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
# случаные значения из равномерного распределения от 0 до 1
np.random.random(5)

array([0.66926072, 0.39508441, 0.24423586, 0.11980845, 0.39569077])

In [20]:
np.random.random((3,3))

array([[0.12796014, 0.96609219, 0.2117336 ],
       [0.92441162, 0.19269344, 0.90314747],
       [0.43387916, 0.01824136, 0.71103378]])

In [21]:
# случайные целый значения
# случайное  число от 0 до 10
np.random.randint(10)

1

In [22]:
# вектор-строка со знач. от 0 до 10 размером (длиной) 5
np.random.randint(10,size=5)

array([8, 5, 2, 9, 0])

In [26]:
# матрица формой 2 на 3 со слууч. знач. от 10 до 20
np.random.randint(10, 20, size=(2,3))

array([[17, 15, 17],
       [15, 18, 12]])

- атрибуты


In [29]:
a=np.random.randint(10, size=(2,3))
a

array([[5, 0, 8],
       [2, 9, 1]])

In [30]:
# размерность массива - кол-во измерений/осей
a.ndim

2

In [31]:
# форма массива
a.shape

(2, 3)

In [32]:
# количество всех элементов
a.size

6

In [33]:
# тип значений
a.dtype

dtype('int32')

In [37]:
a.astype("int8")

array([[5, 0, 8],
       [2, 9, 1]], dtype=int8)