# Pandas

In [5]:
# импортирование необходимых модулей
import numpy as np
import pandas as pd

In [6]:
# !pip install pandas

# Объекты модуля Pandas

- Series

In [7]:
# Series - одномерный массив (вектор-строка) индексированных данных
# Можно создать из списка или массива NumPy
data=pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [9]:
# атрибуты
data.dtype

dtype('float64')

In [10]:
data.shape

(4,)

In [11]:
# значения
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [12]:
data.values[2:]

array([0.75, 1.  ])

In [13]:
# индексы
data.index

RangeIndex(start=0, stop=4, step=1)

In [14]:
np.array(data.index)

array([0, 1, 2, 3], dtype=int64)

In [15]:
list(data.index)

[0, 1, 2, 3]

In [17]:
for i in data.index:
    print(i)

0
1
2
3


In [19]:
# неявные и явные индексы
# неявные индексы - индексы по умолчанию
# явные индексы - кастомизированные индексы
data_2=pd.Series([100, 200, 300, 400], index=['a', 'b', 'c', 'd'])
data_2

a    100
b    200
c    300
d    400
dtype: int64

In [20]:
# использование явных индексов
data_2[0]

100

In [21]:
# создание на базе словаря
popul_dict={
    'Yakutsk': 318768,
    'Neryungri': 57009,
    'Viliuysk': 11095
}

popul=pd.Series(popul_dict)
popul

Yakutsk      318768
Neryungri     57009
Viliuysk      11095
dtype: int64

In [22]:
# максирование 
popul[popul>50000]


Yakutsk      318768
Neryungri     57009
dtype: int64

- DataFrame

In [24]:
# DataFrame - двумерный массив, состоящий из Series-Ов
# таблица
popul

Yakutsk      318768
Neryungri     57009
Viliuysk      11095
dtype: int64

In [26]:
# новые данные
area_dict={
    'Yakutsk': 122,
    'Neryungri': 98.9,
    'Viliuysk': 15
}
cities_data=pd.DataFrame({'Population': popul, 'Area': area_dict})
cities_data

Population   Area
Neryungri       57009   98.9
Viliuysk        11095   15.0
Yakutsk        318768  122.0

In [27]:
# атрибуты
# индекс строк
cities_data.index

Index(['Neryungri', 'Viliuysk', 'Yakutsk'], dtype='object')

In [28]:
# ключи столбцов
cities_data.columns

Index(['Population', 'Area'], dtype='object')

In [29]:
# DataFrame нужно рассматривать как специализированный словарь
cities_data['Population']

Neryungri     57009
Viliuysk      11095
Yakutsk      318768
Name: Population, dtype: int64

In [30]:
# [ключ столбца][индекс строки]
cities_data['Population']['Yakutsk']

318768

# Манипуляции с данными

- срез

In [31]:
data_2

a    100
b    200
c    300
d    400
dtype: int64

In [32]:
# срез по неявным индексам
data_2[1:3]

b    200
c    300
dtype: int64

In [33]:
data_3=pd.Series([10, 20, 30], index=[1, 2, 3])
data_3

1    10
2    20
3    30
dtype: int64

In [34]:
# атрибуд-индексаторы
# для неявных индексов
data_3.iloc[0]

10

In [35]:
# для явных индексов
data_3.loc[1]

10

In [36]:
data_3.iloc[:1]

1    10
dtype: int64

In [37]:
data_3.iloc[:2]

1    10
2    20
dtype: int64